2024/11/03 14:04:32 [error] 29#29: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/inventory HTTP/1.1", upstream: "http://172.18.0.5:5001/api/inventory", host: "localhost", referrer: "http://localhost/catalogo"
2024/11/03 14:04:51 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/inventory HTTP/1.1", upstream: "http://172.18.0.5:5001/api/inventory", host: "localhost"
2024/11/03 14:05:43 [error] 31#31: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /api/inventory HTTP/1.1", upstream: "http://172.18.0.5:5001/api/inventory", host: "localhost", referrer: "http://localhost/catalogo"
